import os
import sys
# Get the directory where the script is located
script_directory = os.path.dirname(os.path.abspath(__file__))
# Go one folder back
rt_cosmik_path = os.path.dirname(script_directory)
parent_directory = rt_cosmik_path
# Append it to sys.path
sys.path.append(str(rt_cosmik_path))
meshes_folder_path = os.path.join(rt_cosmik_path, 'meshes')

import pandas as pd 
import pinocchio as pin 
from pinocchio.visualize import GepettoVisualizer, RVizVisualizer
import numpy as np
from utils.model_utils import build_model_challenge, Robot, get_jcp_global_pos
from utils.ik_utils import RT_IK
from utils.viz_utils import place, Rquat
import time
from xacrodoc import XacroDoc

### Xacro generation 
doc = XacroDoc.from_file("urdf/5dof_mpc_base.urdf.xacro",resolve_packages=False)
doc.to_urdf_file("urdf/human_5dof.urdf")

### Loading human urdf generated by xacro
human = Robot(os.path.join(parent_directory,'urdf/human_5dof.urdf'),os.path.join(parent_directory,'meshes')) 
human_model = human.model
human_data= human.data

pin.framesForwardKinematics(human_model,human_data, pin.neutral(human_model))
pos_ankle_calib = human_data.oMi[human_model.getJointId('ankle_Z')].translation

data_markers = pd.read_csv(os.path.join(rt_cosmik_path,'output/augmented_markers_positions.csv'))
data_keypoints = pd.read_csv(os.path.join(rt_cosmik_path,'output/keypoints_3d_positions.csv'))

result_markers = []
for frame, group in data_markers.groupby("Frame"):
    frame_dict = {row["Marker"]: np.array([row["X"], row["Y"], row["Z"]]) for _, row in group.iterrows()}
    result_markers.append(frame_dict)

result_keypoints = []
for frame, group in data_keypoints.groupby("Frame"):
    frame_dict = {row["Keypoint"]: np.array([row["X"], row["Y"], row["Z"]]) for _, row in group.iterrows()}
    if "Hip" in frame_dict:
        frame_dict["midHip"] = frame_dict.pop("Hip")
    result_keypoints.append(frame_dict)

# VISUALIZATION

viz = GepettoVisualizer(human_model,human.geom_model,human.visual_model)
try:
    viz.initViewer()
except ImportError as err:
    print(
        "Error while initializing the viewer. It seems you should install gepetto-viewer"
    )
    print(err)
    sys.exit(0)

try:
    viz.loadViewerModel("pinocchio")
except AttributeError as err:
    print(
        "Error while loading the viewer model. It seems you should start gepetto-viewer"
    )
    print(err)
    sys.exit(0)

### IK init 
dt = 0.06
q = np.array([np.pi/2,0,0,-np.pi,0]) # init pos
keys_to_track_list = ['Knee', 'midHip', 'Shoulder', 'Elbow', 'Wrist']
dict_dof_to_keypoints = dict(zip(['knee_Z', 'lumbar_Z', 'shoulder_Z', 'elbow_Z', 'hand_fixed'],keys_to_track_list))

lstm_dict = {**result_keypoints[0], **result_markers[0]}
jcp_dict = get_jcp_global_pos(lstm_dict,pos_ankle_calib,'right')

### IK calculations
ik_class = RT_IK(human_model, jcp_dict, q, keys_to_track_list, dt, dict_dof_to_keypoints, False)
t0=time.time()
q = ik_class.solve_ik_sample_casadi()
t1=time.time()
print('Casadi Time to solve', t1-t0)
viz.display(q)
ik_class._q0=q

print(q)
input()

for ii in range(1,len(result_markers)): 
    lstm_dict = {**result_keypoints[ii], **result_markers[ii]}
    jcp_dict = get_jcp_global_pos(lstm_dict,pos_ankle_calib,'right')
    ik_class._dict_m= jcp_dict
    t0 = time.time()
    q = ik_class.solve_ik_sample_quadprog() 
    t1 = time.time()
    print('Quadprog Time to solve', t1-t0)
    viz.display(q)
    ik_class._q0 = q 
    input()
